apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/adityalaxkar/my-first-app-on-k8s.git  # Replace with your repository URL
    targetRevision: HEAD
    path: k8s/applications/python-webapp
  destination:
    server: https://kubernetes.default.svc
    namespace: python-webapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 